.travis.yml, guides-markdown/guides-template.txt, guides/install-linux.html, guides/install-mac.html, guides/install-windows.html, package.json
This update will only have an effect if a user with admin rights to the repo connects with a travis-ci.org account and sets up to use with the github pages repo. This enables automatic building of guides when a commit is made to the master branch, so if new markdown is added (or existing markdown is edited) the guides will be updated automatically. The updates will be deployed to a `gh-pages` branch, which can be set as the default branch for bcoin.io if we want to use this.
=> Added CI Deployment with TravisCI

.travis.yml, guides.html, guides/generate-address.html, guides/install-linux.html, guides/install-mac.html, guides/install-windows.html, guides/op_return.html, guides/scripting.html, utils/createHTML.js
Basically this just adds an id that matches with the title (converted to lowercase, removing anything in parentheses, and replacing spaces with dashes) so that you can link internally within a guide to headers via the markdown. This is useful for long guides (like the advanced crowdfund tx ones currently in PR) where you want to link to somewhere earlier in the guide.
=> automatically add id to all header tags to allow for internal linking

api-docs-slate/source/includes/_coin.md, api-docs-slate/source/includes/_transaction.md
Clarifies indexing options:
* Get coins by outpoints is always available
* Coins API calls only need `index-address` for getting coins by addresses.
* Getting transactions by tx hash need `index-tx`
* Getting transactions by address need both `index-tx` and `index-address`
=> Update indexing notes

guides-markdown/scripting.md
I think more could be done in the way of adding comments describing what's up, specifically around the pattern `input.execute(stack)`  followed by `output.execute(stack);`
If that's of interest I'll make a separate stab as a PR.
=> Remove stray schmutz

api-docs-slate/source/includes/_clients.md, api-docs-slate/source/includes/_coin.md, api-docs-slate/source/includes/_node.md, api-docs-slate/source/includes/_node_rpc.md, api-docs-slate/source/includes/_node_rpc_block.md, api-docs-slate/source/includes/_node_rpc_chain.md, api-docs-slate/source/includes/_node_rpc_general.md, api-docs-slate/source/includes/_node_rpc_mempool.md, api-docs-slate/source/includes/_node_rpc_mining.md, api-docs-slate/source/includes/_node_rpc_network.md, api-docs-slate/source/includes/_node_rpc_tx.md, api-docs-slate/source/includes/_transaction.md, api-docs-slate/source/includes/_wallet.md, api-docs-slate/source/includes/_wallet_accounts.md, api-docs-slate/source/includes/_wallet_admin.md, api-docs-slate/source/includes/_wallet_tx.md, api-docs-slate/source/index.html.md
This PR represents a week or so of testing all examples in the docs, trying every function for cURL, CLI and JS. Most changes were in the JS examples since the structure of the system has changed so much. I am going to continue to add commits to this branch to clean up typos, and add a few more examples for functions that were not listed before. I'm not totally happy with the style of all my fixes, (some examples are written for testnet and others for regtest, for example). So I intend to keep working on the docs and make every single example copy-paste-executable from top to bottom in all three interfaces. I figured this was a good point to squash commits and submit for review while I clean up the rest.
=> Update all examples - major overhaul

api-docs-slate/source/index.html.md
addresses https://github.com/bcoin-org/bcoin/issues/474 and support requests on slack/IRC. Docs don't match current npm version...
=> docs: breaking version upgrade notice

guides-markdown/building-plugins.md
Was "Buidling" instead of "Building"
=> Fix typo in "building plugins" title

api-docs-slate/source/includes/_wallet.md
These params were recently changed to match cURL and JS methods: https://github.com/bcoin-org/bclient/commit/3ed63cd2838be1629125ab4b8eadc079caa2d4a2
Then later changed again to these new names: https://github.com/bcoin-org/bclient/commit/0fa8536f552c091d777bfbbd62c6167929c782dd
I'm starting to get #support requests on slack about this, so here's an update to the docs.
=> update bwallet-cli mkwallet params

api-docs-slate/source/includes/_clients.md, api-docs-slate/source/index.html.md
Here we specify that the API key must be generated and provided by the user, and add a little tip on how to generate one with `bcrypto`
=> Add tip to create strong API key

guides-markdown/wallets.md
The example in its previous state throws an error when run with the newest bcoin version. This fixes the errors, renames a variable for clarity and removes some trailing whitespace.
=> Use new key and address derivation methods

guides-markdown/events.md
Quick update!
See https://github.com/bcoin-org/bcoin/blob/master/lib/wallet/http.js#L866-L879
Wallet events that get emitted out the socket return `wallet-id` and a `details` object only. The `TX` object is ignored by the socket-emitting handler.
=> Events guide: Wallet event only emits tx-details

api-docs-slate/source/includes/_wallet_events.md
Addresses https://github.com/bcoin-org/bcoin-org.github.io/issues/111
Revises API-docs regarding wallet events and sockets. Refers to new bcoin.io guide, update examples and event names. Mentions `bsock`!
=> API docs: update wallet events

api-docs-slate/source/includes/_wallet.md
Examples in the docs mostly have the fee rate set at 500 sats, but those transactions won't get mined, even in regtest! 
see: https://github.com/bcoin-org/bcoin/blob/master/lib/protocol/networks.js#L863
Brought to attention by a user in slack #support
=> API docs: increase example fees

api-docs-slate/source/includes/_wallet.md, api-docs-slate/source/stylesheets/_custom.scss
Addresses https://github.com/bcoin-org/bcoin-org.github.io/issues/80 by including `passphrase` in the wallet options. This also replaces `receiveDepth` and `changeDepth` with `accountDepth` [which was changed in the code](https://github.com/bcoin-org/bcoin/commit/976fd46da5d7c1064ed3184c90ca2d9d05e3354a) about 2 years ago 😬
Some parameters for `createWallet` are [not avail to the http API](https://github.com/bcoin-org/bcoin/blob/master/lib/wallet/http.js#L274-L285) and I've indicated that as well.
Picked a few nits with grammar and capitalization. Put the wallet options chart in the actual parameter list for `create a wallet` (they were separated by a few pages before), and finally rearranged the order of the sections in the wallet doc so it read top-down if this was your first time ever …
=> api-docs: update wallet client and options

README.md
As requested. Adds instructions on test-rendering markdown and using Prism JS to add new language recognition.
=> Readme: convert markdown and prismJS

CNAME
Apparently Github can't handle multiple CNAMEs
=> Reverting previous change

guides-markdown/segwit.md
Just noticed this as I was skimming through some docs. Pretty sure you mean SHA256 here.
=> Fix incorrect MD5 references

api-docs-slate/source/includes/_clients.md, api-docs-slate/source/includes/_wallet.md, api-docs-slate/source/index.html.md, guides-markdown/beginners.md
I interacted with a user on slack who was confused about the purpose and interaction of API keys, wallet/admin tokens and the `wallet-auth` parameter. I think this addition to the api-docs lays it all out pretty clearly.
Bonus: fixed all the broken links to bcoin docs/configuration which is spelled with a lower-case 'c' now since https://github.com/bcoin-org/bcoin/pull/713
=> api-docs: explain wallet-auth

api-docs-slate/source/includes/_node.md, api-docs-slate/source/includes/_wallet_admin.md
The `reset` command has been missing from the api-docs.
It was originally documented only in an older version of `bcoin/docs/CLI.md` that was cleared out in the recent docs overhaul: https://github.com/bcoin-org/bcoin/commit/c64ccf215e527f4588bf767312afc9668bc3c75a
I'm not sure if it was kept of the website docs for a reason, but it is useful (essential actually) for wallet rescans in SPV mode. I've walked a few users through it on slack.
=> api-docs: add reset

guides-markdown/bcoin-clock.md, guides-markdown/beginners.md, guides-markdown/connect-local-nodes.md, guides-markdown/crowdfund-tx.md, guides-markdown/vps-setup.md
Closes https://github.com/bcoin-org/bcoin-org.github.io/issues/154
replace all `npm install bcoin` with `git clone...` instructions instead.
Also updated node and npm requirements in the beginner's guide.
=> guides: install from git not npm

api-docs-slate/source/includes/_node_sockets.md
See https://github.com/bcoin-org/bcoin/issues/887
When I wrote these examples and tested them, I didn't try testing the false-negative. If I had, I'd have noticed that transactions that shouldn't have matched the filter were getting emitted down the socket as well. See above issue for explanation.
The examples now match the code in bcoin -- see `pool.watchAddress()` and `walletDB.addPathMap()` for examples.
=> api-docs: correct filter add and set examples

api-docs-slate/source/includes/_coin.md, api-docs-slate/source/includes/_node.md, api-docs-slate/source/includes/_node_rpc.md, api-docs-slate/source/includes/_node_rpc_block.md, api-docs-slate/source/includes/_node_rpc_chain.md, api-docs-slate/source/includes/_node_rpc_general.md, api-docs-slate/source/includes/_node_rpc_mempool.md, api-docs-slate/source/includes/_node_rpc_mining.md, api-docs-slate/source/includes/_node_rpc_network.md, api-docs-slate/source/includes/_node_rpc_tx.md, api-docs-slate/source/includes/_transaction.md, api-docs-slate/source/includes/_wallet.md, api-docs-slate/source/includes/_wallet_accounts.md, api-docs-slate/source/includes/_wallet_admin.md, api-docs-slate/source/includes/_wallet_rpc.md, api-docs-slate/source/includes/_wallet_sockets.md, api-docs-slate/source/includes/_wallet_tx.md, api-docs-slate/source/index.html.md
Address https://github.com/bcoin-org/bcoin-org.github.io/pull/160#issuecomment-544709129
Depends on:
https://github.com/bcoin-org/bcoin/pull/889 (bcoin-cli: expose estimateFee)
https://github.com/bcoin-org/bcoin/pull/890 (bwallet-cli: add sign parameter)
...and may need to be updated depending on the progress of those PRs.
Updates for `2.0.0-dev`:
- Display updated `get info` response including filter indexer and version number
- Add `/header` and details, examples
- Add `/filter` and details, examples
- Add details and examples for existing call `/fee` (see https://github.com/bcoin-org/bcoin/pull/889 )
- Link commands in table to individual sections of the docs for better UX.
- Deprecate `bclient` for `NodeClient` and `WalletClient` and get those from `bcoin` instead
- Replace all …
=> api-docs: updates for 2.0.0-dev

guides-markdown/multisig-cli.md
Walks through setting up multisig wallets, creating and signing transactions, using just the command line. Demonstrates how easy bcoin is to use for multisig schemes without writing any code. This process will be especially helpful when ported over to Handshake, since some faucet recipients created multisig addresses, and there is no documentation on how to construct a wallet to redeem it!
=> guides: multisig on the command line

api-docs-slate/source/includes/_clients.md, api-docs-slate/source/includes/_node.md, api-docs-slate/source/includes/_wallet.md, api-docs-slate/source/index.html.md
Closes https://github.com/bcoin-org/bcoin/issues/940 
and fixes a typo in broadcast tx.
=> Nits: add host to client options, clarify params to broadcast tx

api-docs-slate/source/includes/_clients.md
https://bcoin.io/api-docs/index.html?javascript#using-javascript-clients , Connecting to nodes that have SSL( `https`) enabled is using [bclient](https://www.npmjs.com/package/bclient) not specified in the documentation
=> Added ssl to javascript client connection 
