bcoin-org/bcoin-org.github.io

guides-markdown/op_return.md, guides/op_return.html
This PR adds a guide for creating `OP_RETURN` output transactions.
=> Add OP_RETURN guide

guides-markdown/multisig-tx.md, guides/multisig-tx.html
I haven't added this guide to `guide.html`. You can choose the place.
=> Multisignature Transactions

guide-generator.js, guides-markdown/multisig-tx.md, guides-markdown/scripting.md, guides-markdown/working-with-txs.md, utils/generatePages.js
I should have separated these, but I noticed this problem on the way.
So fixes Generator all/file versions.
Adds guide from JJ working with Txs.
=> Fix generator, add guide from JJ

guides-markdown/beginners.md, guides.html, guides/beginners.html, guides/crowdfund-tx.html, guides/generate-address.html, guides/install-linux.html, guides/install-mac.html, guides/multisig-tx.html, guides/op_return.html, guides/scripting.html, guides/working-with-txs.html
Not entirely sure why it thinks I made a bunch of the changes you did yesterday. Might want to double check things.
=> Added Beginners Guide

guides-markdown/wallets.md
This is my first attempt at writing a guide. I tried to cover all the key topics and provide examples using different approaches. I'd be happy to get any feedback/revisions you may have or suggestions for other areas this guide should cover. Also, I'm not sure if the title is funny silly or stupid silly, if you think it's the latter I'll take no offense if you suggest I change it.
This addresses #38.
=> Guide to wallet structure and creating wallets with bcoin

api-docs-slate/source/includes/_node.md, api-docs-slate/source/includes/_transaction.md
This is a resubmission of #23 to update the markdown files.
=> Adding `confirmations` to get block and get tx example responses

api-docs-slate/source/includes/_wallet.md, api-docs-slate/source/includes/_wallet_accounts.md
This is a resubmission of #42 to update markdown files.
=> Updating examples for watchOnly wallet & account creation

api-docs-slate/source/includes/_wallet_events.md, api-docs-slate/source/index.html.md, api-docs/index.html
Adds wallet events documentation from the bcoin read me
=> add wallet events

guides.html, guides/crowdfund-tx.html, page-templates/guides-archive.html, page-templates/guides-template.html, utils/createHTML.js
Using backbone templating engine (as in the guides archive) to insert meta into html template.
=> insert post meta into guide template

api-docs-slate/source/includes/_wallet.md, api-docs/index.html
Update wallet send and create methods.
=> Update parameters for wallet create and send

api-docs-slate/source/includes/_wallet.md
Improve docs for wallet creation.
Fix some styles for easier copying.
Related:
[#339](https://github.com/bcoin-org/bcoin/issues/339)
=> Fix wallet docs

guides-markdown/building-plugins.md
added a guide on building plugins
=> guide: add plugins guide

guides-markdown/crowdfund-tx.md, guides-markdown/generate-address.md, guides-markdown/multisig-tx.md, guides-markdown/op_return.md, guides-markdown/scripting.md, guides-markdown/wallets.md, guides-markdown/working-with-txs.md
Almost done. Segwit needs to be updated @nodar-chkuaselidze
=> guides: update for bcoin master

guides-markdown/cltv.md
A guide for creating time locked transactions. Includes guide for mock transactions and live transactions on a regtest network. Would love any feedback on where this can be improved in terms of code or clarity of explanation!
=> new cltv guide

api-docs-slate/source/includes/_wallet.md
Clarifies issues https://github.com/bcoin-org/bcoin/issues/163 and https://github.com/bcoin-org/bcoin/issues/510
=> api-docs: clarify unconfirmed balance

api-docs-slate/source/includes/_node_rpc_block.md, api-docs-slate/source/includes/_node_rpc_general.md, api-docs-slate/source/includes/_node_rpc_mempool.md, api-docs-slate/source/includes/_node_rpc_tx.md, api-docs-slate/source/includes/_wallet.md, api-docs-slate/source/includes/_wallet_rpc.md, api-docs-slate/source/index.html.md
50+ RPC commands documented for cURL, CLI and JS!
Also a few style fixes and additional cross-references in existing docs.
=> api-docs: all wallet RPC commands

guides-markdown/wallets.md
Don't forget to zip up afterwards!
=> Add missing closing brace

guides-markdown/events.md
Thanks to a user on slack for catching this typo :-)
=> guides: events: chainEntry.from not a function

guides-markdown/wallets.md
Add a section in the wallet guide that briefly explains how to play with Paths.
=> Add path example

api-docs-slate/source/includes/_node_sockets.md, api-docs-slate/source/includes/_sockets.md, api-docs-slate/source/includes/_wallet_sockets.md, api-docs-slate/source/index.html.md
Closes https://github.com/bcoin-org/bcoin-org.github.io/issues/139
To render locally for review: https://github.com/bcoin-org/bcoin-org.github.io/blob/staging/api-docs-slate/README.md
=> api-docs: update sockets calls and events

guides-markdown/crowdfund-tx.md, guides-markdown/segwit.md, guides-markdown/wallets.md
=> patch bcoin.keyring typo

api-docs-slate/source/index.html.md
Update version and date on the first page of the api docs.
=> api-docs: update version and date
